# User config
author: "Shantao Cao"
tagline: "Shantao Cao's Portfolio"
description: "Northwestern University Masters Science in Robotics Student. "
keywords: "ROS, Robotics, Perception, Control"
email: "shantaocao2023@u.northwestern.edu"
resume: "https://drive.google.com/file/d/1fgWrFIwFW5HkfGvrniAQ8aSEaXHehRiH/view?usp=sharing"
# linkedin: "https://www.linkedin.com/in/james-avtges/"
github: "https://github.com/rhit-caos1"


# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed