# User config
author: "Shantao Cao"
tagline: "Shantao Cao Portfolio"
description: "Shantao Cao's Portfolio"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "shantaocao2023@northwestern.edu"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed