# User config
author: "Shantao Cao"
tagline: "Shantao Cao's Portfolio"
description: "A Current of Northwestern University MS in Robotics Student."
keywords: "ROS, Robotics, Perception, Control"
email: "shantaocao2023@u.northwestern.edu"
resume: "https://drive.google.com/file/d/1JsrGW4EbiTKPTaaRNOJLorj6GlF-TgTB/view?usp=sharing"
linkedin: "https://www.linkedin.com/in/shantao-cao-9875b4192/"
github: "https://github.com/rhit-caos1"


# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed