# User config
author: "Shantao Cao"
tagline: "Shantao Cao's Portfolio"
description: "Hello! I am a Northwestern University MS in Robotics Student which expected to graduate in March 2024. I earned my Bachelor's degree in Mechanical Engineering and a minor in Robotics from Ros2-Hulman Institute of Technology in 2022. Personally like implement exsiting technology to solve some real life problems and learn everything about transportation. Feel free to contact me about any of my projects!"
keywords: "ROS, Robotics, Perception, Control"
email: "shantaocao2023@u.northwestern.edu"
resume: "https://drive.google.com/file/d/1JTnlzoqYw-OvFRTp8WbLMn-aGWKKS2zS/view?usp=sharing"
linkedin: "https://www.linkedin.com/in/shantao-cao-9875b4192/"
github: "https://github.com/rhit-caos1"


# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed